version: '3'

services:
  app:
    build: app/
    volumes:
      - ../nginx:/etc/nginx
    container_name: app-service
  prx:
    build: prx/
    ports:
      - 80:8080
    volumes:
      - ./prx/nginx:/etc/nginx
    container_name: prx-service
    depends_on:
      - app